"""Added freelancer profile fields

Revision ID: 123087be5e13
Revises: 059d2995f11e
Create Date: 2026-07-14 10:54:34.901788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123087be5e13'
down_revision = '059d2995f11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancerprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('portfolio', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freelancerprofiles', schema=None) as batch_op:
        batch_op.drop_column('portfolio')
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('education')
        batch_op.drop_column('experience')
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
