"""Added delivery fields to order

Revision ID: 763fe017423b
Revises: 123087be5e13
Create Date: 2026-07-23 19:58:11.223914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763fe017423b'
down_revision = '123087be5e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('delivered_file')

    # ### end Alembic commands ###
